kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: autonfs
provisioner: autonfs/nfs
mountOptions:
  - vers=4.1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
spec:
  storageClassName: autonfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
